# Steps to go for
qc_and_merge_step: true
taxonomic_inventory: true
cgc_step: false
reads_functional_annotation: false
assemble: false

# Global
threads: 40

# Run wf partially
processed_reads: 
contigs_file: 

# fastp parameters
detect_adapter_for_pe: false
overrepresentation_analysis: false
min_length_required: 100
force_polyg_tail_trimming: 
base_correction: false
qualified_phred_quality: 
unqualified_percent_limit: 
disable_trim_poly_g:
overlap_len_require: 
cut_right: false
correction: false

# Assembly
memory: 550
min-contig-len: 200

# Combined Gene Caller // the size is in MB
cgc_chunk_size: 50

# Taxonomic inference using Diamond and the contigs
diamond_maxTargetSeqs: 1

# Functional annotation
protein_chunk_size_IPS: 10000      # 100
protein_chunk_size_eggnog: 10000   # 800
protein_chunk_size_hmm: 5000       # 20 

# The following variables should be considered only in case 
# the user has already ran some of the first steps and wants to 
# run the following parts of the workflow. 
# For example, you have ran the quality contron and the rna prediction steps
# and you would like to go just for the assembly step. 



# Input files for running the CGC step; 
# this step is required if you are about to run the functional annotation step and 
# the one of CGC has not been performed earlier
# The CGC step returns the: 
# check_value
# cgc_results_faa
# files, required for the functional annotation step
input_fasta: 
maskfile: 


# Required files for running the functional annotation step


