# Global 
get_rna_prediction: true
cgc_step: true
reads_functional_annotation: false
assemble: true
threads: 20

# Run wf partially
processed_reads: 
contigs_file: 

# fastp parameters
detect_adapter_for_pe: false
overrepresentation_analysis: false
min_length_required: 100
force_polyg_tail_trimming: 
base_correction: false
qualified_phred_quality: 
unqualified_percent_limit: 
disable_trim_poly_g:
overlap_len_require: 
cut_right: false
correction: false

# Assembly
memory: 550
min-contig-len: 200

# Combined Gene Caller // the size is in MB
cgc_chunk_size: 50

# Taxonomic inference using Diamond and the contigs
diamond_maxTargetSeqs: 1

# Functional annotation
protein_chunk_size_IPS: 100
protein_chunk_size_eggnog: 100
protein_chunk_size_hmm: 20
# protein_chunk_size_IPS: 10000
# protein_chunk_size_eggnog: 100000
# protein_chunk_size_hmm: 50000
