# # Get data from ENA 
# run_accession_number: ""
# private_data: false
# ena_api_username: ""
# ena_api_password: ""

# Global 
run_qc: true
rna_prediction_reads_level: true
assemble: true
rna_prediction_contigs_level: true
funct_annot: false

threads: 20


# Run wf partially
processed_reads: 
contigs_file: 


# fastp parameters
detect_adapter_for_pe: false
overrepresentation_analysis: false
min_length_required: 75
force_polyg_tail_trimming: 
base_correction: false
qualified_phred_quality: 
unqualified_percent_limit: 
disable_trim_poly_g:
overlap_len_require: 
cut_right: false
correction: false

# Functional annotation
cgc_chunk_size: 100
diamond_maxTargetSeqs: 1


# Assembly

# memory: 550
# min-contig-len: 250
memory: 550
min-contig-len: 50



protein_chunk_size_IPS: 100
protein_chunk_size_eggnog: 100
protein_chunk_size_hmm: 20
# protein_chunk_size_IPS: 10000
# protein_chunk_size_eggnog: 100000
# protein_chunk_size_hmm: 50000
